default_platform(:ios)



platform :ios do
  desc "Description of what the lane does"
  lane :just_build_app do
    gym(
      scheme: "AppleWatchApp\ Watch\ App",
      destination: "generic/platform=watchOS",
      export_method: "development"
    )
  end
end
